const schema = {
	Address: [
		'delete',
		'getAreas',
		'getCities',
		'getSettlements',
		'getStreet',
		'getWarehouses',
		'getWarehouseTypes',
		'save',
		'searchSettlements',
		'searchSettlementStreets',
		'update',
	],
	Common: [
		'getBackwardDeliveryCargoTypes',
		'getCargoDescriptionList',
		'getCargoTypes',
		'getMessageCodeText',
		'getOwnershipFormsList',
		'getPackList',
		'getPalletsList',
		'getPaymentForms',
		'getServiceTypes',
		'getTimeIntervals',
		'getTiresWheelsList',
		'getTypesOfCounterparties',
		'getTypesOfPayers',
		'getTypesOfPayersForRedelivery',
	],
	Counterparty: [
		'delete',
		'getCounterpartyAddresses',
		'getCounterpartyOptions',
		'getCounterpartyContactPersons',
		'getCounterparties',
		'save',
		'update',
		{ method: 'saveCounterparty', alias: 'save', deprecated: true },
		{ method: 'updateCounterparty', alias: 'update', deprecated: true },
		{ method: 'deleteCounterparty', alias: 'delete', deprecated: true },
		{ method: 'saveContactPerson', model: 'ContactPerson', deprecated: true },
		{ method: 'updateContactPerson', model: 'ContactPerson', deprecated: true },
		{ method: 'deleteContactPerson', model: 'ContactPerson', deprecated: true },
	],
	ContactPerson: [
		'delete',
		'save',
		'update',
	],
	InternetDocument: [
		'delete',
		'generateReport',
		'getDocumentDeliveryDate',
		'getDocumentList',
		'getDocumentPrice',
		'getStatusDocuments',
		'save',
		'update',
	],
	ScanSheet: [
		'deleteScanSheet',
		'insertDocuments',
		'getScanSheet',
		'getScanSheetList',
		'removeDocuments',
	],
	AdditionalService: [
		'delete',
		'getChangeEWOrdersList',
		'getRedirectionOrdersList',
		'getReturnOrdersList',
		'getReturnReasons',
		'getReturnReasonsSubtypes',
		'CheckPossibilityChangeEW',
		'CheckPossibilityCreateReturn',
		'save',
	],
	AdditionalServiceGeneral: [
		'delete',
		'checkPossibilityForRedirecting',
		'save',
	],
};

export default schema;
