name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: install
        run: npm ci
        env:
          CI: true
      - name: run tests
        run: npm test
